dist: xenial
language: php
env:
  global:
  - setup=stable
matrix:
  fast_finish: true
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3
cache:
  directories:
  - "$HOME/.composer/cache"
services:
- memcached
- redis-server
- mysql
before_install:
- phpenv config-rm xdebug.ini || true
- echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
- printf "\n" | pecl install -f redis
- travis_retry composer self-update
install:
- if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction
  --prefer-stable --no-suggest; fi
script: vendor/bin/phpunit
notifications:
  email: false
  slack:
    rooms:
      secure: BvBX2Vvhui5e2cT9/eIJf8g+owltQHGtV/hSoiKbCOmo9QwOwjXrVWMNmIRq78gBpE4iTUxI2rtaYj45fvwwC0DzglA2F/+wlflSIEpXjosI0wg2ffxmVRamlEwuIH0rKnb/jwFYYNoZ+PydcVX/RHZd+ZbUhYB/EBkKWEiQJZnOgtk/VzbAOw5X5ezZBonXy4NhxjOjLDAfjnGoXqQMGSjvdonhSYj9H/Ga8ZuusgYAhJugtXCknWFzmvtEgWf7u/ltU2kiygccAK6g2r1JSPEVShlLrJ7KODLigxAL+YekP3DLoAXGTEUMH8OyFne+MhutHDHfqvUSG5gf53wWlQsVC3kz2ZEbRhB8i5utD4nWGQ3JrvJTw0alJw+Hlw5tzJKUh0N+2P15+oRE9cF5QDPwaPUjUg9qcCRAckqLqSkX/g4uOv0I23IBTb9vhHXp9C9OlhruT3xUplM426wxcGYUgYZrXYbE2cHa341+7Db2ObqeFSMXcE/YKfBwtlz0Jdb9PgZCkP6GBaRnRp8iaGnCzTr9M8psaHyoHx/g41tDvgTuBEseGFr+xb8hIYmbR/M4BP6HFg3poMM6e9tQq42wlFeg0RlQnbCX1ahCHlvkW3/MccFrjPj2oplGcyKn9IhAKW++zqa6JeeoPF12SI0DnrMz+KxZ8nA6u0L9rDY=
    template:
    - "%{repository_slug} (%{commit}) : %{message} %{foo} "
    - "Build details: %{build_url}"
    on_success: change
    on_failure: change
